version: "3"
services:
  mariadb:
    image: mariadb:10
    env_file: /home/ecelis/var/services/.env
    ports:
      - "3306:3306"
    volumes:
      - "/srv/mariadb:/var/lib/mysql"
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  postgresql:
    image: mdillon/postgis:10
    env_file: /home/ecelis/var/services/.env
    ports:
      - "5432:5432"
    volumes:
      - "/srv/postgres:/var/lib/postgresql/data/pgdata"
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8088:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
  tonali:
    image: wordpress:5.3.2-php7.2-apache
    ports:
      - "8092:80"
    volumes:
      - "/srv/tonaliartesanal.com:/var/www/html"
    env_file: ./.env
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
